import type { FraudCase, AttackAgent, SimulatedSystem } from "./types";

export const mockCases: FraudCase[] = [
  {
    id: "TXN-8A2F9B",
    type: "APP Fraud",
    amount: 4230,
    riskScore: 92,
    status: "critical",
    account: "usr_7291a",
    timestamp: "2025-05-15T09:23:00Z",
    region: "UK",
  },
  {
    id: "TXN-3C7D1E",
    type: "Unauthorised",
    amount: 1850,
    riskScore: 78,
    status: "warning",
    account: "usr_4812b",
    timestamp: "2025-05-15T08:45:00Z",
    region: "US East",
  },
  {
    id: "TXN-6F4A2D",
    type: "Collusion",
    amount: 12400,
    riskScore: 95,
    status: "critical",
    account: "usr_9103c",
    timestamp: "2025-05-15T07:12:00Z",
    region: "EU West",
  },
  {
    id: "TXN-1B8E3F",
    type: "First-Party",
    amount: 320,
    riskScore: 45,
    status: "review",
    account: "usr_5527d",
    timestamp: "2025-05-15T06:58:00Z",
    region: "APAC",
  },
  {
    id: "TXN-9D5C7A",
    type: "APP Fraud",
    amount: 8900,
    riskScore: 88,
    status: "critical",
    account: "usr_3346e",
    timestamp: "2025-05-15T05:30:00Z",
    region: "UK",
  },
  {
    id: "TXN-2E6B4C",
    type: "Unauthorised",
    amount: 560,
    riskScore: 32,
    status: "cleared",
    account: "usr_8891f",
    timestamp: "2025-05-15T04:15:00Z",
    region: "US West",
  },
  {
    id: "TXN-7G3H1I",
    type: "Collusion",
    amount: 6750,
    riskScore: 87,
    status: "warning",
    account: "usr_2204g",
    timestamp: "2025-05-15T03:48:00Z",
    region: "EU West",
  },
  {
    id: "TXN-4J8K2L",
    type: "First-Party",
    amount: 1100,
    riskScore: 55,
    status: "review",
    account: "usr_6678h",
    timestamp: "2025-05-15T02:22:00Z",
    region: "LATAM",
  },
];

export const mockAttackAgents: AttackAgent[] = [
  {
    id: "agt-001",
    name: "APP Fraud Prober",
    vector: "app_fraud",
    status: "completed",
    targetRegion: "UK",
    intensity: "high",
    progress: 100,
    findings: 14,
    startedAt: "2025-05-15T08:00:00Z",
  },
  {
    id: "agt-002",
    name: "Account Takeover Bot",
    vector: "unauthorised",
    status: "running",
    targetRegion: "US East",
    intensity: "medium",
    progress: 67,
    findings: 8,
    startedAt: "2025-05-15T09:15:00Z",
  },
  {
    id: "agt-003",
    name: "Refund Abuse Scanner",
    vector: "first_party",
    status: "idle",
    targetRegion: "EU West",
    intensity: "low",
    progress: 0,
    findings: 0,
    startedAt: null,
  },
  {
    id: "agt-004",
    name: "Ring Detection Stress",
    vector: "collusion",
    status: "running",
    targetRegion: "APAC",
    intensity: "high",
    progress: 34,
    findings: 3,
    startedAt: "2025-05-15T09:30:00Z",
  },
];

export const mockSystems: SimulatedSystem[] = [
  {
    id: "sys-uk-01",
    name: "PayPal UK Gateway",
    region: "UK",
    fraudWeaknesses: ["app_fraud", "unauthorised"],
    firewallStrength: 72,
    isOnline: true,
  },
  {
    id: "sys-us-east-01",
    name: "PayPal US East Hub",
    region: "US East",
    fraudWeaknesses: ["unauthorised", "first_party"],
    firewallStrength: 85,
    isOnline: true,
  },
  {
    id: "sys-eu-west-01",
    name: "PayPal EU West Node",
    region: "EU West",
    fraudWeaknesses: ["collusion", "app_fraud"],
    firewallStrength: 68,
    isOnline: true,
  },
  {
    id: "sys-apac-01",
    name: "PayPal APAC Relay",
    region: "APAC",
    fraudWeaknesses: ["first_party", "collusion"],
    firewallStrength: 60,
    isOnline: false,
  },
  {
    id: "sys-latam-01",
    name: "PayPal LATAM Gateway",
    region: "LATAM",
    fraudWeaknesses: ["app_fraud", "unauthorised", "first_party"],
    firewallStrength: 55,
    isOnline: true,
  },
  {
    id: "sys-us-west-01",
    name: "PayPal US West Hub",
    region: "US West",
    fraudWeaknesses: ["collusion"],
    firewallStrength: 90,
    isOnline: true,
  },
];

export const regions = [
  "All Regions",
  "UK",
  "US East",
  "US West",
  "EU West",
  "APAC",
  "LATAM",
];

export const vectorLabels: Record<string, string> = {
  app_fraud: "APP Fraud",
  unauthorised: "Unauthorised Fraud",
  first_party: "First-Party Fraud",
  collusion: "Collusion Fraud",
};
